/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaCrearTelefono extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCrearTelefono
     */
    public VentanaCrearTelefono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearTelefono = new javax.swing.JPanel();
        lblCrearTelefonoNumero = new javax.swing.JLabel();
        lblCrearTelefonoTipo = new javax.swing.JLabel();
        txtCrearTelefonoNumero = new javax.swing.JTextField();
        txtCrearTelefonoTipo = new javax.swing.JTextField();
        btnAceptarCrearTelefono = new javax.swing.JButton();
        btnCancelarCrearTelefono = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelCrearTelefono.setBackground(new java.awt.Color(255, 204, 204));
        panelCrearTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Nuevo Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        lblCrearTelefonoNumero.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCrearTelefonoNumero.setText("Numero:");

        lblCrearTelefonoTipo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCrearTelefonoTipo.setText("Tipo:");

        txtCrearTelefonoNumero.setToolTipText("Ingrese el nuevo telefono de la persona");

        txtCrearTelefonoTipo.setToolTipText("Ingrese el nuevo tipo de telefono");

        btnAceptarCrearTelefono.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAceptarCrearTelefono.setText("Aceptar");
        btnAceptarCrearTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearTelefonoActionPerformed(evt);
            }
        });

        btnCancelarCrearTelefono.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCancelarCrearTelefono.setText("Cancelar");
        btnCancelarCrearTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearTelefonoLayout = new javax.swing.GroupLayout(panelCrearTelefono);
        panelCrearTelefono.setLayout(panelCrearTelefonoLayout);
        panelCrearTelefonoLayout.setHorizontalGroup(
            panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTelefonoLayout.createSequentialGroup()
                .addGroup(panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTelefonoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCrearTelefonoTipo)
                            .addComponent(lblCrearTelefonoNumero))
                        .addGap(87, 87, 87)
                        .addGroup(panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCrearTelefonoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrearTelefonoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCrearTelefonoLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnAceptarCrearTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarCrearTelefono)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelCrearTelefonoLayout.setVerticalGroup(
            panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTelefonoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearTelefonoNumero)
                    .addComponent(txtCrearTelefonoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearTelefonoTipo)
                    .addComponent(txtCrearTelefonoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelCrearTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCrearTelefono)
                    .addComponent(btnCancelarCrearTelefono))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCrearTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCrearTelefonoActionPerformed

    private void btnAceptarCrearTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarCrearTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCrearTelefono;
    private javax.swing.JButton btnCancelarCrearTelefono;
    private javax.swing.JLabel lblCrearTelefonoNumero;
    private javax.swing.JLabel lblCrearTelefonoTipo;
    private javax.swing.JPanel panelCrearTelefono;
    private javax.swing.JTextField txtCrearTelefonoNumero;
    private javax.swing.JTextField txtCrearTelefonoTipo;
    // End of variables declaration//GEN-END:variables
}
