/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaCrearOperadoraTelefonica extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCrearOperadoraTelefonica
     */
    public VentanaCrearOperadoraTelefonica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNuevaOperadora = new javax.swing.JPanel();
        lblCodigoOperadora = new javax.swing.JLabel();
        lblNombreOperadora = new javax.swing.JLabel();
        txtCodigoCrearOperadora = new javax.swing.JTextField();
        txtNombreCrearOperadora = new javax.swing.JTextField();
        btnAceptarCrearOperadora = new javax.swing.JButton();
        btnCancelarCrearOperadora = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelNuevaOperadora.setBackground(new java.awt.Color(204, 255, 204));
        panelNuevaOperadora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Nueva Operadora Telefonica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N

        lblCodigoOperadora.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCodigoOperadora.setText("Codigo:  ");

        lblNombreOperadora.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNombreOperadora.setText("Nombre:");

        txtCodigoCrearOperadora.setToolTipText("Ingrese el nuevo codigo de la Operadora");
        txtCodigoCrearOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCrearOperadoraActionPerformed(evt);
            }
        });

        txtNombreCrearOperadora.setToolTipText("Ingrese el nuevo nombre de la Operadora");
        txtNombreCrearOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCrearOperadoraActionPerformed(evt);
            }
        });

        btnAceptarCrearOperadora.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAceptarCrearOperadora.setText("Aceptar");
        btnAceptarCrearOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearOperadoraActionPerformed(evt);
            }
        });

        btnCancelarCrearOperadora.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCancelarCrearOperadora.setText("Cancelar");
        btnCancelarCrearOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearOperadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNuevaOperadoraLayout = new javax.swing.GroupLayout(panelNuevaOperadora);
        panelNuevaOperadora.setLayout(panelNuevaOperadoraLayout);
        panelNuevaOperadoraLayout.setHorizontalGroup(
            panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevaOperadoraLayout.createSequentialGroup()
                .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevaOperadoraLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoOperadora)
                            .addComponent(lblNombreOperadora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevaOperadoraLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptarCrearOperadora)
                        .addGap(27, 27, 27)))
                .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCodigoCrearOperadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreCrearOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNuevaOperadoraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCancelarCrearOperadora)))
                .addGap(23, 23, 23))
        );
        panelNuevaOperadoraLayout.setVerticalGroup(
            panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaOperadoraLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoOperadora)
                    .addComponent(txtCodigoCrearOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreOperadora)
                    .addComponent(txtNombreCrearOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelNuevaOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCrearOperadora)
                    .addComponent(btnCancelarCrearOperadora))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNuevaOperadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNuevaOperadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCrearOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCrearOperadoraActionPerformed

    private void btnAceptarCrearOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarCrearOperadoraActionPerformed

    private void txtCodigoCrearOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCrearOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCrearOperadoraActionPerformed

    private void txtNombreCrearOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCrearOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCrearOperadoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCrearOperadora;
    private javax.swing.JButton btnCancelarCrearOperadora;
    private javax.swing.JLabel lblCodigoOperadora;
    private javax.swing.JLabel lblNombreOperadora;
    private javax.swing.JPanel panelNuevaOperadora;
    private javax.swing.JTextField txtCodigoCrearOperadora;
    private javax.swing.JTextField txtNombreCrearOperadora;
    // End of variables declaration//GEN-END:variables
}
