/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */

package ec.edu.ups.java.ejemplo.diez.vista;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private VentanaCrearPersona ventanaCrearPersona;
    private VentanaCrearOperadoraTelefonica ventanaCrearOperadoraTelefonica;
    private VentanaCrearTelefono ventanaCrearTelefono;
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        PersonaMenu = new javax.swing.JMenu();
        menuItemCrearPersona = new javax.swing.JMenuItem();
        menuItemActualizarPersona = new javax.swing.JMenuItem();
        menuItemBuscarPersona = new javax.swing.JMenuItem();
        menuItemEliminarPersona = new javax.swing.JMenuItem();
        menuItemListarPersona = new javax.swing.JMenuItem();
        OperadoraTelefonicaMenu = new javax.swing.JMenu();
        menuItemCrearOperadora = new javax.swing.JMenuItem();
        menuItemActualizarOperadora = new javax.swing.JMenuItem();
        menuItemBuscarOperadora = new javax.swing.JMenuItem();
        menuItemEliminarOperadora = new javax.swing.JMenuItem();
        menuItemListarOperadora = new javax.swing.JMenuItem();
        TelefonoMenu = new javax.swing.JMenu();
        menuItemCrearTelefono = new javax.swing.JMenuItem();
        menuItemActualizarTelefono = new javax.swing.JMenuItem();
        menuItemEliminarTelefono = new javax.swing.JMenuItem();
        menuItemBuscarTelefono = new javax.swing.JMenuItem();
        menuItemListarTelefono = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PersonaMenu.setMnemonic('f');
        PersonaMenu.setText("Persona");
        PersonaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaMenuActionPerformed(evt);
            }
        });

        menuItemCrearPersona.setMnemonic('o');
        menuItemCrearPersona.setText("Crear");
        menuItemCrearPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuItemCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearPersonaActionPerformed(evt);
            }
        });
        PersonaMenu.add(menuItemCrearPersona);

        menuItemActualizarPersona.setMnemonic('s');
        menuItemActualizarPersona.setText("Actualizar");
        menuItemActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarPersonaActionPerformed(evt);
            }
        });
        PersonaMenu.add(menuItemActualizarPersona);

        menuItemBuscarPersona.setMnemonic('a');
        menuItemBuscarPersona.setText("Buscar");
        menuItemBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarPersonaActionPerformed(evt);
            }
        });
        PersonaMenu.add(menuItemBuscarPersona);

        menuItemEliminarPersona.setMnemonic('x');
        menuItemEliminarPersona.setText("Eliminar");
        menuItemEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarPersonaActionPerformed(evt);
            }
        });
        PersonaMenu.add(menuItemEliminarPersona);

        menuItemListarPersona.setText("Listar");
        menuItemListarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarPersonaActionPerformed(evt);
            }
        });
        PersonaMenu.add(menuItemListarPersona);

        menuBar.add(PersonaMenu);

        OperadoraTelefonicaMenu.setMnemonic('e');
        OperadoraTelefonicaMenu.setText("Operadora Telefónica");
        OperadoraTelefonicaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadoraTelefonicaMenuActionPerformed(evt);
            }
        });

        menuItemCrearOperadora.setMnemonic('t');
        menuItemCrearOperadora.setText("Crear");
        menuItemCrearOperadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuItemCrearOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearOperadoraActionPerformed(evt);
            }
        });
        OperadoraTelefonicaMenu.add(menuItemCrearOperadora);

        menuItemActualizarOperadora.setMnemonic('y');
        menuItemActualizarOperadora.setText("Actualizar");
        menuItemActualizarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarOperadoraActionPerformed(evt);
            }
        });
        OperadoraTelefonicaMenu.add(menuItemActualizarOperadora);

        menuItemBuscarOperadora.setMnemonic('p');
        menuItemBuscarOperadora.setText("Buscar");
        menuItemBuscarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarOperadoraActionPerformed(evt);
            }
        });
        OperadoraTelefonicaMenu.add(menuItemBuscarOperadora);

        menuItemEliminarOperadora.setMnemonic('d');
        menuItemEliminarOperadora.setText("Eliminar");
        menuItemEliminarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarOperadoraActionPerformed(evt);
            }
        });
        OperadoraTelefonicaMenu.add(menuItemEliminarOperadora);

        menuItemListarOperadora.setText("Listar");
        menuItemListarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarOperadoraActionPerformed(evt);
            }
        });
        OperadoraTelefonicaMenu.add(menuItemListarOperadora);

        menuBar.add(OperadoraTelefonicaMenu);

        TelefonoMenu.setMnemonic('h');
        TelefonoMenu.setText("Teléfono");
        TelefonoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoMenuActionPerformed(evt);
            }
        });

        menuItemCrearTelefono.setMnemonic('c');
        menuItemCrearTelefono.setText("Crear");
        menuItemCrearTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearTelefonoActionPerformed(evt);
            }
        });
        TelefonoMenu.add(menuItemCrearTelefono);

        menuItemActualizarTelefono.setMnemonic('a');
        menuItemActualizarTelefono.setText("Actualizar");
        menuItemActualizarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarTelefonoActionPerformed(evt);
            }
        });
        TelefonoMenu.add(menuItemActualizarTelefono);

        menuItemEliminarTelefono.setText("Eliminar");
        menuItemEliminarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarTelefonoActionPerformed(evt);
            }
        });
        TelefonoMenu.add(menuItemEliminarTelefono);

        menuItemBuscarTelefono.setText("Buscar");
        menuItemBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarTelefonoActionPerformed(evt);
            }
        });
        TelefonoMenu.add(menuItemBuscarTelefono);

        menuItemListarTelefono.setText("Listar");
        TelefonoMenu.add(menuItemListarTelefono);

        menuBar.add(TelefonoMenu);

        menuOpciones.setText("Opciones");
        menuOpciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuOpcionesMenuSelected(evt);
            }
        });

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemSalir);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBuscarPersonaActionPerformed

    private void menuItemCrearOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearOperadoraActionPerformed
        // TODO add your handling code here:
        if(ventanaCrearOperadoraTelefonica==null){
            ventanaCrearOperadoraTelefonica = new VentanaCrearOperadoraTelefonica();
            desktopPane.add(ventanaCrearOperadoraTelefonica);
            
            
        }
        ventanaCrearOperadoraTelefonica.setVisible(true);
    }//GEN-LAST:event_menuItemCrearOperadoraActionPerformed

    private void menuItemListarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarOperadoraActionPerformed

    private void menuItemEliminarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEliminarOperadoraActionPerformed

    private void menuItemBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBuscarTelefonoActionPerformed

    private void menuOpcionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuOpcionesMenuSelected
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuOpcionesMenuSelected

    private void menuItemActualizarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemActualizarOperadoraActionPerformed

    private void menuItemBuscarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBuscarOperadoraActionPerformed

    private void menuItemListarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarPersonaActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearPersonaActionPerformed
        if (ventanaCrearPersona == null){
            ventanaCrearPersona=new VentanaCrearPersona();
            desktopPane.add(ventanaCrearPersona);
        }
       
        ventanaCrearPersona.setVisible(true);
        
    }//GEN-LAST:event_menuItemCrearPersonaActionPerformed

    private void menuItemActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemActualizarPersonaActionPerformed

    private void menuItemEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEliminarPersonaActionPerformed

    private void menuItemCrearTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearTelefonoActionPerformed
        if (ventanaCrearTelefono == null){
            ventanaCrearTelefono=new VentanaCrearTelefono();
            desktopPane.add(ventanaCrearTelefono);
        }
        ventanaCrearTelefono.setVisible(true);
    }//GEN-LAST:event_menuItemCrearTelefonoActionPerformed

    private void menuItemActualizarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemActualizarTelefonoActionPerformed

    private void menuItemEliminarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEliminarTelefonoActionPerformed

    private void PersonaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonaMenuActionPerformed

    private void OperadoraTelefonicaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadoraTelefonicaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperadoraTelefonicaMenuActionPerformed

    private void TelefonoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu OperadoraTelefonicaMenu;
    private javax.swing.JMenu PersonaMenu;
    private javax.swing.JMenu TelefonoMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemActualizarOperadora;
    private javax.swing.JMenuItem menuItemActualizarPersona;
    private javax.swing.JMenuItem menuItemActualizarTelefono;
    private javax.swing.JMenuItem menuItemBuscarOperadora;
    private javax.swing.JMenuItem menuItemBuscarPersona;
    private javax.swing.JMenuItem menuItemBuscarTelefono;
    private javax.swing.JMenuItem menuItemCrearOperadora;
    private javax.swing.JMenuItem menuItemCrearPersona;
    private javax.swing.JMenuItem menuItemCrearTelefono;
    private javax.swing.JMenuItem menuItemEliminarOperadora;
    private javax.swing.JMenuItem menuItemEliminarPersona;
    private javax.swing.JMenuItem menuItemEliminarTelefono;
    private javax.swing.JMenuItem menuItemListarOperadora;
    private javax.swing.JMenuItem menuItemListarPersona;
    private javax.swing.JMenuItem menuItemListarTelefono;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuOpciones;
    // End of variables declaration//GEN-END:variables

}
