/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaActualizarPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaActualizarPersona
     */
    public VentanaActualizarPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCedulaActualizarPersona = new javax.swing.JLabel();
        lblNombreActualizarPersona = new javax.swing.JLabel();
        lblFechaNacimientoActualizarPersona = new javax.swing.JLabel();
        txtCedulaActualizarPersona = new javax.swing.JTextField();
        txtNombreActualizarPersona = new javax.swing.JTextField();
        txtFechaNacimientoActualizarPersona = new javax.swing.JTextField();
        btnAceptarActualizarPersona = new javax.swing.JButton();
        btnCancelarActualizarPersona = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        lblCedulaActualizarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCedulaActualizarPersona.setText("Cedula:");

        lblNombreActualizarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNombreActualizarPersona.setText("Nombre:");

        lblFechaNacimientoActualizarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFechaNacimientoActualizarPersona.setText("Fecha de Nacimiento:");

        txtCedulaActualizarPersona.setToolTipText("Ingrese la nueva cedula de la persona");
        txtCedulaActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActualizarPersonaActionPerformed(evt);
            }
        });

        txtNombreActualizarPersona.setToolTipText("Ingrese el nuevo nombre de de la persona");
        txtNombreActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizarPersonaActionPerformed(evt);
            }
        });

        txtFechaNacimientoActualizarPersona.setToolTipText("Ingrese la nueva fecha de nacimineto de la persona");

        btnAceptarActualizarPersona.setText("Aceptar");
        btnAceptarActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActualizarPersonaActionPerformed(evt);
            }
        });

        btnCancelarActualizarPersona.setText("Cancelar");
        btnCancelarActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnAceptarActualizarPersona)
                .addGap(45, 45, 45)
                .addComponent(btnCancelarActualizarPersona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedulaActualizarPersona)
                    .addComponent(lblNombreActualizarPersona)
                    .addComponent(lblFechaNacimientoActualizarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreActualizarPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaActualizarPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimientoActualizarPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaActualizarPersona)
                    .addComponent(txtCedulaActualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActualizarPersona)
                    .addComponent(txtNombreActualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoActualizarPersona)
                    .addComponent(txtFechaNacimientoActualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarActualizarPersona)
                    .addComponent(btnCancelarActualizarPersona))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActualizarPersonaActionPerformed

    private void txtCedulaActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActualizarPersonaActionPerformed

    private void btnAceptarActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActualizarPersonaActionPerformed

    private void btnCancelarActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActualizarPersonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarActualizarPersona;
    private javax.swing.JButton btnCancelarActualizarPersona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedulaActualizarPersona;
    private javax.swing.JLabel lblFechaNacimientoActualizarPersona;
    private javax.swing.JLabel lblNombreActualizarPersona;
    private javax.swing.JTextField txtCedulaActualizarPersona;
    private javax.swing.JTextField txtFechaNacimientoActualizarPersona;
    private javax.swing.JTextField txtNombreActualizarPersona;
    // End of variables declaration//GEN-END:variables
}
